### ISSUE TITLE
ArgumentException on running il2cpp deployed builds

### ISSUE THREAD

**Issue by ghost** [manhunterita/PATCH#16]
The Launcher does not function when deployed with the il2cpp scripting backend.

The output log shows an `ArgumentException: Invalid path` was thrown.

![screenshot_1 1](https://user-images.githubusercontent.com/47191093/52005244-3d61ec00-2497-11e9-91a0-6b245d52f164.png)

**Comment by MiTschMR** [comment]
Hello

I have this issue too, will there be an update soon that fixes this?

Otherwise great asset, many thanks to you.

**Comment by manhunterita** [comment]
Is this issue relative to the new 2.2.0 or are you talking about the old 2.1.7?

**Comment by MiTschMR** [comment]
I am using the new version 2.2.0.

**Comment by manhunterita** [comment]
Can you share with me your logs from 2.2.0?

**Comment by MiTschMR** [comment]
These are the logs from the player.log:

`ArgumentException: Invalid path
  at System.IO.Path.GetDirectoryName (System.String path) [0x00000] in <00000000000000000000000000000000>:0 
  at MHLab.Patch.Core.Settings..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at MHLab.Patch.Launcher.Scripts.Launcher.Awake () [0x00000] in <00000000000000000000000000000000>:0 
`

**Comment by manhunterita** [comment]
Ok, I'll take a look at this under IL2CPP!

**Comment by manhunterita** [comment]
I solved this issue! It will be included in the next 2.2.2 release.

**Comment by MiTschMR** [comment]
Perfect, thank you very much.
