### ISSUE TITLE
Add url for debugging purposes

### ISSUE THREAD

**Issue by MiTschMR** [manhunterita/PATCH#21]
Hi

Using PATCH v 2.2.0. 

Can you please add the url to the stacktrace for debugging purposes? I am having troubles with my launcher updates, they are getting an error 404. I would like to know, which url they attempt to connect to. 

![image](https://user-images.githubusercontent.com/47354974/81158110-f01cd600-8f87-11ea-9ed3-12fb8215df8c.png)

**Comment by manhunterita** [comment]
Yeah, a customer already reported this to me. I already added the URL in the error reporting, it will be out with 2.2.1! If you need it right now, contact me on Discord with your invoice number!

**Comment by MiTschMR** [comment]
I have found out that this only happens, when you upload the first launcher version to the webserver and have the first launcher start your game. It then generates this error. When using a newer launcher version this does not occur.
