### ISSUE TITLE
Change ProgressBar.Value to ProgressBar.Progress

### ISSUE THREAD

**Issue by StarPilot00** [manhunterita/PATCH#22]

**Comment by StarPilot00** [comment]
Problem caused by installing new PATCH version over old P.A.T.C.H..
So two versions of ProgressBar.cs are in the folder and conflicting (.Value vs .Progress).

**Comment by manhunterita** [comment]
ProgressBar.Value has been renamed as ProgressBar.Progress. It will be available in the next release (2.2.2).
