### ISSUE TITLE
Custom Versioning

### ISSUE THREAD

**Issue by manutoo** [manhunterita/PATCH#23]
I'd like to be able to enter my version as x.y.z (with of course only incrementing the values).

eg: 36.20200620.1

Having the possibility to show a custom version field instead of selecting the release type would do the trick.

It should also have the possibility to enter the version for the 1st build.

**Comment by manhunterita** [comment]
Versioning logic has been abstracted. Now you can implement IVersion and IVersionFactory interfaces to create your own versioning logic.

This change will be included in the next 2.2.2 release.
