### ISSUE TITLE
"Our servers are not responding" after setting everything up correctly

### ISSUE THREAD

**Issue by davidrochin** [manhunterita/PATCH#27]
I followed your documentation but all I get is that message.

My local server is accesible:
![image](https://user-images.githubusercontent.com/7517516/88962753-1ccd4a80-d264-11ea-89db-66a8b61e81ff.png)

My configuration is okay:
![image](https://user-images.githubusercontent.com/7517516/88962808-32db0b00-d264-11ea-8e5b-f5348da5804a.png)

But all I get is:
![image](https://user-images.githubusercontent.com/7517516/88962836-3b334600-d264-11ea-8622-60df915b4279.png)

And I get no errors in the console.

**Comment by manhunterita** [comment]
You missed to upload the Builds folder in the path: you should be able to navigate to this file if everything is set up correctly `http://localhost/patch/Builds/builds_index.json`

**Comment by Haxsen** [comment]
@emanzione I've followed your tutorial doc and confirmed `http://localhost/patch/Builds/builds_index.json` opens up correctly and builds are set up well too BUT still the launcher says `"Our servers are not responding"` in the standalone build while it works well in the unity editor.

Edit: code stripping may be at fault as I read on https://discord.com/channels/143316585233252352/189475555240837124/1102675608875565130

Edit 2: yes code stripping was at fault

**Comment by emanzione** [comment]
Great, glad you solved it!
