### ISSUE TITLE
Unauthorized exception when trying to download a JSON

### ISSUE THREAD

**Issue by ThuzzLightyear** [manhunterita/PATCH#28]
We use an s3 bucket with authentication, but when trying to download a JSON file using 'DownloadsManager.DownloadString' I get an (401) Unauthorized exception. In the 'FileDownloader' you have the credentials exposed, but the 'DownloadsManager' does not make use of these credentials.

**Comment by manhunterita** [comment]
I exposed the NetworkCredentials for DownloadsManager too. Now you can just inject your credentials in the UpdatingContext object.
It will be pushed together with the next release.
