### ISSUE TITLE
Slice/Chunk Parallel Transfers needed for High-Latency / Distant Connections

### ISSUE THREAD

**Issue by Wentil** [manhunterita/PATCH#34]
Despite multi-threading, we are experiencing slow transfer times on large files (like piggs) for users who are in Europe with high ping times / latency, as each large file is only serviced by a single thread/channel. Adding 16-32 slice/chunk parallel transfers would allow high-latency users to more properly make use of their available bandwidth, as although each channel would be limited in transfer speed due to latency, running them in parallel would stack the overall speed. Of potential use in terms of integration at the file transfer layer is Aria2 (https://aria2.github.io/) which is a very stable and mature transfer tool that supports splitting files into 16 separate slices / transfer channels, as well as HTTP, HTTPS, FTP, Bittorrent and more.

**Comment by manhunterita** [comment]
The feature has been completed. It will be released in the next 2.6.0 update.
